vse: &vse
   docker:
      - image: circleci/node:8.11.3
ansible: &ansible
   docker:
      - image: circleci/python:3.8.1
version: 2.1
jobs:
   build:
      <<: *vse
      steps:
         - checkout
         - run: npm install
         - run: npm run test
         - run: npm run build
         - persist_to_workspace:
            root: .
            paths:
               - .
   deploy:
      <<: *ansible
      steps:
         - attach_workspace:
            at: .
         - run: pip3 install ansible boto boto3
         - run: chmod 400 ./ansible/ansible.pem
         - add_ssh_keys:
            fingerprints:
            - "78:4c:f0:df:c9:85:77:18:a5:67:04:fb:c5:c6:b0:27"
         - run:
            command: ansible-playbook ./ansible/ec2_deploy.yml --user ubuntu --key-file ./ansible/ansible.pem --vault-pass-file ./ansible/group_vars/all/.pass.txt
            environment:
               ANSIBLE_HOST_KEY_CHECKING: False 

workflows:
   version: 2.1
   build:
      jobs:
         - build
         - deploy:
            requires:
            - build
            filters:
               branches:
                  only: main
